### ISSUE TITLE
App has stopped

### ISSUE THREAD

**Issue by husseinsheikh** [hktorab/Splash-Screen#1]
I have added the app as you have shown in the YouTube video but when I run the app it keeps getting error app has stopped, Open app again

Any hint where I may have gone wrong?

**Comment by hktorab** [comment]
Sorry for being late to answer your question,I hope you solve it. If you unfortunately failed to solve the problem then  I need to know about your ERROR,without it I won't be able to solve your problem. Search Log cat to find out your ERROR.  I have given a snap of log cat. 

![capture1](https://user-images.githubusercontent.com/17125763/31327322-597940de-acf0-11e7-902e-3dd2adc7185b.PNG)
